##################################################
#
# COMMON
#
##################################################

# Note: we need the spring.application.xy properties as one-liner for logback-spring.xml
spring.application.id: CAR
spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'

spring:
  datasource:
    username: parking_admin
    password: G8xkJsKcQe5gKnPYHIEa
    url: jdbc:postgresql://localhost:5002/carversation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openai:
  api:
    key: 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