##################################################
#
# COMMON
#
##################################################

# Note: we need the spring.application.xy properties as one-liner for logback-spring.xml
spring.application.id: CAR
spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'

spring:
  datasource:
    username: <username>
    password: <password>
    url: jdbc:postgresql://localhost:5002/carversation
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect